apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-guestbook
    tier: db
  name: nodejs-guestbook-mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30454
  selector:
    app: nodejs-guestbook
    tier: db
